# Generated by Django 3.1.5 on 2021-02-09 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Giseo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, verbose_name='логин')),
                ('password', models.CharField(max_length=100, verbose_name='пароль')),
                ('place', models.CharField(max_length=150, verbose_name='городской округ / Муниципальный район')),
                ('locality', models.CharField(max_length=150, verbose_name='населённый пункт')),
                ('type_of_oo', models.CharField(max_length=150, verbose_name='тип ОО')),
                ('educational_organization', models.CharField(max_length=150, verbose_name='образовательная организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'giseo',
                'verbose_name_plural': "giseo's",
                'ordering': ['user', 'login', 'place'],
                'managed': True,
            },
        ),
    ]
