# Generated by Django 3.1.6 on 2021-02-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='населённый пункт')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='городской округ / Муниципальный район')),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_oo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='тип ОО')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.locality', verbose_name='населённый пункт')),
            ],
        ),
        migrations.AddField(
            model_name='locality',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.place', verbose_name='городской округ / Муниципальный район'),
        ),
        migrations.CreateModel(
            name='Educational_organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='образовательная организация')),
                ('type_of_oo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.type_of_oo', verbose_name='тип ОО')),
            ],
        ),
        migrations.AlterField(
            model_name='giseo',
            name='educational_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.educational_organization', verbose_name='образовательная организация'),
        ),
        migrations.AlterField(
            model_name='giseo',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.locality', verbose_name='населённый пункт'),
        ),
        migrations.AlterField(
            model_name='giseo',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.place', verbose_name='городской округ / Муниципальный район'),
        ),
        migrations.AlterField(
            model_name='giseo',
            name='type_of_oo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.type_of_oo', verbose_name='тип ОО'),
        ),
    ]
