# Generated by Django 3.1.6 on 2021-02-11 12:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20210211_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational_organization',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='образовательная организация'),
        ),
        migrations.AlterField(
            model_name='giseo',
            name='locality',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='place', chained_model_field='place', on_delete=django.db.models.deletion.CASCADE, to='Account.locality', verbose_name='населённый пункт'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='населённый пункт'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='городской округ / Муниципальный район'),
        ),
        migrations.AlterField(
            model_name='type_of_oo',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='тип ОО'),
        ),
    ]
