# Generated by Django 3.1.6 on 2021-02-11 13:23

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20210211_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giseo',
            name='educational_organization',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='type_of_oo', chained_model_field='type_of_oo', on_delete=django.db.models.deletion.CASCADE, to='Account.educational_organization', verbose_name='образовательная организация'),
        ),
        migrations.AlterField(
            model_name='giseo',
            name='type_of_oo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='locality', chained_model_field='locality', on_delete=django.db.models.deletion.CASCADE, to='Account.type_of_oo', verbose_name='тип ОО'),
        ),
    ]
