#  Copyright (c) 2021.  TheFox

# Generated by Django 3.1.7 on 2021-04-27 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(max_length=50, verbose_name='время начала')),
                ('time_end', models.TimeField(max_length=50, verbose_name='время конца')),
                ('date', models.DateField(null=True, verbose_name='дата')),
                ('affair', models.CharField(help_text='Дела должны быть в виде обычного текста', max_length=200, verbose_name='дело')),
                ('note', models.CharField(blank=True, help_text='Заметки должны быть в виде обычного текста', max_length=200, verbose_name='заметка')),
                ('homework',
                 models.CharField(blank=True, default=None, help_text='Домашнее задание должны быть в виде обычного текста', max_length=200, verbose_name='домашнее задание')),
                ('is_ready', models.BooleanField(default=False, help_text='Готово? принимает только значение True или False', verbose_name='готово?')),
                ('user',
                 models.ForeignKey(help_text='Id пользователя должен быть в виде одного числа', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                   verbose_name='id пользователя')),
                ],
            options={
                'verbose_name': 'расписание',
                'ordering': ['date'],
                'managed': True,
            },
        ),
    ]
