# Generated by Django 3.1.5 on 2021-02-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user_id',
            new_name='user',
        ),
    ]
