# Generated by Django 3.1.6 on 2021-02-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_auto_20210208_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='homework',
            field=models.CharField(blank=True, default=None, help_text='Домашнее задание должны быть в виде обычного текста', max_length=200, verbose_name='домашнее задание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='note',
            field=models.CharField(blank=True, help_text='Заметки должны быть в виде обычного текста', max_length=200, verbose_name='заметка'),
        ),
    ]
